[package]
name = "rust_tutorial"
version = "0.1.0"
authors = ["gabriel <gabrielgoller123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md-5 = "0.9.1"
time = "0.2.22"
hex-literal = "0.3.1"